config/routes.rb
# frozen_string_literal: true

# routes
require 'sidekiq/web'
require 'sidekiq/cron/web'
Rails.application.routes.draw do
  # devise_for :users
  # resources :users do
  #   post :follow, to: 'users/follows#create', as: :follow
  #   delete :follow, to: 'users/follows#destroy', as: :unfollow
  # end

  # resources :posts do
  #   resources :photos, only: [:create]
  #   resources :likes, only: %i[create destroy], shallow: true
  #   resources :comments, shallow: true
  # end
  # mount ActionCable.server => '/cable'
  # mount Sidekiq::Web => '/sidekiq'
  # get '/search', to: 'users#search'
  # get 'followers', to: 'users#followers'
  # resources :stories
  # resources :requests
  # root 'posts#index'

  namespace :api do
    get :followers, to: 'stories#followers'
    resources :stories
  end
end

app/models/user.rb
# frozen_string_literal: true

# rubocop required comment
class User < ApplicationRecord
  include Followable
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :stories, dependent: :destroy
  mount_uploader :image, ImageUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence: true, length: { maximum: 20 }
  validates :email, format: Devise.email_regexp, uniqueness: true, presence: true
  validate :password_complexity

  def password_complexity
    return if password.blank? || password =~ /^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,70}$/

    errors.add :password,
               'Length should be 8-70 characters and include: 1 uppercase, 1 lowercase, 1 digit and 1 special character'
  end

  def follow_status(current_user)
    return 'pending' unless current_user.following?(id)

    follower_relationships.find_by(follower_id: current_user.id, following_id: id).status
  end
end

app/controllers/users/follows_controller.rb
# frozen_string_literal: true

# class for follows
class Users::FollowsController < ApplicationController
  before_action :set_user

  def create
    return unless current_user.follow(@user.id)
  end

  def destroy
    return unless current_user.unfollow(@user.id)

    respond_to do |format|
      format.js { render action: :create }
    end
  end

  private

  def set_user
    @user = User.find_by(id: params[:user_id])
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# User controller
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @user_posts = current_user.posts
  end

  def search
    @user_posts = current_user.posts
    @query = params[:query]
    @usersearch = User.find_by(username: @query)
    if @usersearch.present?
      if current_user.username == @usersearch.username
        render 'index'
      else
        render 'search'
      end
    else
      flash[:error] = 'User not found'
      redirect_to posts_path
    end
  end

  private

  def find_user
    @user = User.find_by(id: params[:id])
    return if @user

    flash[:danger] = 'User does not exist!'
    redirect_to root_path
  end

  def user_params
    params.require(:user).permit(:username, :email)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/_follow_btn.html.erb
<div id="follow-btn">
  <% if user.account_type == 'public' %>
    <% if current_user.following?(user) %>
      <%= link_to user_unfollow_path(user.id), method: :delete, remote: true do %>
        <button class="btn btn-success ml-4">Unfollow</button>
      <% end %>
    <% else %>
      <%= link_to user_follow_path(user.id), method: :post, remote: true do %>
        <button class="btn btn-success ml-4">Follow</button>
      <% end %>
    <% end %>
  <% end %>
  <% if user.account_type == 'private' %>
    <% if current_user.following?(user) && user.follower_relationships.find_by(follower_id: current_user.id).status == 'accepted' %>
      <%= link_to user_unfollow_path(user.id), method: :delete, remote: true do %>
        <button class="btn btn-success ml-4">Unfollow</button>
      <% end %>
    <% elsif current_user.following?(user) && user.follower_relationships.find_by(follower_id: current_user.id).status == 'pending' %>
      <%= link_to user_unfollow_path(user.id), method: :delete, remote: true do %>
        <button class="btn btn-secondary ml-4">Requested</button>
      <% end %>
    <% else %>
      <%= link_to user_follow_path(user.id), method: :post, remote: true do %>
        <button class="btn btn-success ml-4">Follow</button>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/users/_gravatar.html.erb
<% if current_user.image.present? %>
  <%= link_to edit_user_registration_path(current_user) do %>
    <%= image_tag current_user.image.url, class: "rounded-circle mt-4", width: "50%", height: "90%" %>
  <% end %>
<% else %>
  <%= link_to edit_user_registration_path(current_user) do %>
    <%= image_tag 'gravatar-pic.jpg', class: "rounded-circle mt-4", width: "50%", height: "90%" %>
  <% end %>
<% end %>

app/views/users/followers.html.erb
<% @followers.each do |f| %>
  <h4><%= f.username %></h4>
  <li><%= f.email %></li>
<% end %>

app/views/users/index.html.erb
<div class="row">
  <div class="col-4 text-center mb-3">
    <%= render 'gravatar' %>
  </div>
  <div class="col-8">
    <div class="row mt-5">
      <h1 class="username col-5 mt-2"><%= current_user.username %></h1>
      <button class="btn btn-success col-2 mx-1 m-auto"><%= link_to 'Edit User', edit_user_registration_path(current_user), class: "text-white" %></button>
      <%= link_to "Logout User", destroy_user_session_path, class: "btn btn-success col-1 m-auto mx-2" %>
    </div>
    <div class="row mt-3">
      <h3><%= current_user.email %></h3>
    </div>
    <div class="mt-3">
      <h5><%= current_user.bio %></h5>
    </div>
    <%= link_to 'Create Post', posts_path, class: "btn btn-success" %>
    <%= link_to 'Add to story', stories_path, class: "btn btn-success" %>
  </div>
  <hr>
</div>
<div>
  <% @user_posts.each do |post| %>
    <div class = "card">
      <div class = "card-header">
        <h4><%= post.user.username %></h4>
      </div>
      <p class= "mx-2" ><%= post.content %></p>
      <%= link_to  posts_path do %>
        <div class="text-center mb-3">
          <%# <%= image_tag post.photos.first.image.url, class: "rounded-circle", width: "30%", height: "300px" %> %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
</div>
<%= render 'shared/footer' if current_user %>

app/views/users/search.html.erb
<div class="row justify-content-md-center profile-wrapper">
  <div class="col-md-4 text-center">
    <% if @usersearch.image.present? %>
      <%= image_tag @usersearch.image.url, class: "rounded-circle mt-4", width: "50%", height: "90%" %>
    <% else %>
      <%= image_tag 'gravatar-pic.jpg', class: "rounded-circle mt-4", width: "50%", height: "90%" %>
    <% end %>
  </div>
  <div class="col-md-8">
    <div class="row mt-5">
      <h1 class="username col-5 mt-2"><%= @usersearch.username %></h1>
    </div>
    <div class="row mt-3">
      <h3 class="email"><%= @usersearch.email %></h3>
    </div>
    <%= render 'follow_btn', user: @usersearch %>
  </div>
</div>