config/routes.rb
# frozen_string_literal: true

# routes
require 'sidekiq/web'
require 'sidekiq/cron/web'
Rails.application.routes.draw do
  # devise_for :users
  # resources :users do
  #   post :follow, to: 'users/follows#create', as: :follow
  #   delete :follow, to: 'users/follows#destroy', as: :unfollow
  # end

  # resources :posts do
  #   resources :photos, only: [:create]
  #   resources :likes, only: %i[create destroy], shallow: true
  #   resources :comments, shallow: true
  # end
  # mount ActionCable.server => '/cable'
  # mount Sidekiq::Web => '/sidekiq'
  # get '/search', to: 'users#search'
  # get 'followers', to: 'users#followers'
  # resources :stories
  # resources :requests
  # root 'posts#index'

  namespace :api do
    get :followers, to: 'stories#followers'
    resources :stories
  end
end

app/models/story.rb
# frozen_string_literal: true

# rubocop required comment
class Story < ApplicationRecord
  has_many :photos, as: :imageable, dependent: :destroy
  validates :caption, presence: true
end

app/controllers/api/stories_controller.rb
# frozen_string_literal: true

class Api::StoriesController < ApplicationController
  # before_action :authenticate_user!
  skip_before_action :verify_authenticity_token
  before_action :set_story, only: %i[destroy]
  def index
    @stories = Story.all
    @story = Story.new
    @photos = Photo.all
    @stories_with_photos = [@stories, @photos]
    render json: @stories_with_photos
  end

  def create
    @user = User.find(1)
    @story = @user.stories.create(story_params)
    @story.save
    render json: @story
  end

  def show
    @stories = Story.limit(1000).includes(:photos, :user)
    render json: @stories
  end

  def destroy
    @story.destroy
    render json: { notice: 'Story was successfully removed.' }
  end

  def followers
    user = User.find(13)
    @followers = user.followers
    render json: @followers
  end

  private

  def set_story
    @story = Story.find(params[:id])
    return if @story

    render json: { error: 'Story does not exist' }, status: :not_found
    redirect_to root_path
  end

  def story_params
    params.require(:story).permit(:caption)
  end
end

app/controllers/stories_controller.rb
# frozen_string_literal: true

# stories controller
class StoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_story, only: %i[destroy]

  def index
    @stories = Story.all.limit(1000).includes(:photos, :user)
    @story = Story.new
  end

  def create
    @story = current_user.stories.create(story_params)
    image = params[:images]
    ActiveRecord::Base.transaction do
      if @story.save
        image.each do |img|
          @story.photos.create(image: img)
        end
        flash[:notice] = 'Story Created'
      else
        flash[:alert] = 'Something went wrong!'
      end
    end
    redirect_to stories_path
  end

  def show
    @stories = Story.all.limit(1000).includes(:photos, :user)
  end

  def destroy
    ActiveRecord::Base.transaction do
      if @story.destroy
        flash[:notice] = 'Story deleted'
      else
        flash[:alert] = 'Something went wrong ...'
      end
    rescue ActiveRecord::RecordNotDestroyed => e
      render json: {
        error: e.to_s
      }, status: :not_found
    end
    redirect_to stories_path
  end

  private

  def set_story
    @story = Story.find(params[:id])
    authorize @story
    return if @story

    flash[:danger] = 'Story does not exist'
    redirect_to root_path
  end

  def story_params
    params.require(:story).permit(:caption)
  end
end

app/helpers/api/stories_helper.rb
module Api::StoriesHelper
end

app/helpers/stories_helper.rb
# frozen_string_literal: true

module StoriesHelper
end

app/views/stories/_create_story.html.erb
<%= form_for story, :html => {:multipart => true, :class => "p-0 border-0"} do |f| %>
  <%= f.text_field :caption, class: "form-control", placeholder: "Insert caption", required: true %>
  <%= file_field_tag "images[]", type: :file, multiple: true , required: true %>
  <%= f.submit "Story", class: "btn btn-default btn-success mt-2 pull-right" %>
<% end %>

app/views/stories/_story_body.html.erb
<% stories.each do |story| %>
  <div class="card w-50 mb-5">
    <div class="card-header text-center">
      <h4><%= story.user.username %></h4>
    </div>
    <br>
    <p class= "mx-2" ><%= story.caption %>
      <% if story.user == current_user %>
        <%= link_to story_path(story), method: :delete, class: "ml-auto mx-0 my-auto pull-right" do %>
          <i class = "far fa-trash-alt pull-right mx-2" aria-hidden = "true"></i>
        <% end %>
        <%= link_to story_path(story) do %>
          <i class = "far fa-circle pull-right" aria-hidden = "true"></i>
        <% end %>
      </p>
    <% end %>
    <% story.photos.each do |photo| %>
      <div class="text-center mb-3">
        <%= image_tag photo.image.url, class: "rounded-circle", width: "30%"%>
      </div>
    <% end %>
    <div class="light-color mx-3 my-2">created <%= time_ago_in_words(story.created_at) %> ago</div>
  </div>
<% end %>

app/views/stories/index.html.erb
<div class="d-flex flex-column align-items-center mt-3">
  <div class="col-xl-7 col-lq-8 col-md-10 col-sm-11 post-card">
    <div class="card">
      <div class="card-header">
        Create story
      </div>
      <div class="card-body">
        <%= render 'create_story', story: @story %>
      </div>
    </div>
    <br>
    <%= render 'story_body', stories: @stories  %>
  </div>
</div>

app/views/stories/show.html.erb
<div class="mt-5">
  <% @stories.each do |story| %>
    <div class="card w-100 mb-5">
      <div class="card-header text-center">
        <h4><%= story.user.username %></h4>
      </div>
      <br>
      <p class= "mx-2 h5" ><%= story.caption %>
        <% if story.user == current_user %>
          <%= link_to story_path(story), method: :delete, class: "ml-auto mx-0 my-auto pull-right" do %>
            <i class = "far fa-trash-alt pull-right mx-2" aria-hidden = "true"></i>
          <% end %>
          
        </p>
      <% end %>
      <% story.photos.each do |photo| %>
        <div class="text-center mb-3">
          <%= image_tag photo.image.url, width: "30%"%>
        </div>
      <% end %>
    </div>
  <% end %>
  <%= link_to "Back", :back, class: "btn btn-success" %>
</div>